- hosts: yps
  become: yes
  gather_facts: no

  tasks:
    - name: Start sshd
      service: name=sshd state=started enabled=yes

    - name: Place sshd Configuration file
      template:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0600
      register: template_result

    - name: Apply sshd Configuration
      service: name=sshd state=restarted
      when: template_result is changed
